name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

trigger:
  batch: true
  branches:
    include:
    - master
    - refs/tags/*
pr:
  branches:
    include:
    - master

jobs:
- template: run-tox-env.yml
  parameters:
    jobs:
      fix_lint: null
