parameters:
  artifact_feed: ""
  pypi_remote: ""
  dependsOn: []

jobs:
  - job: publish
    dependsOn: ${{ parameters.dependsOn }}
    condition: succeeded()
    pool: { vmImage: "ubuntu-latest" }
    variables:
      TMPDIR: $(Build.BinariesDirectory)
      PIP_NO_WARN_SCRIPT_LOCATION: "0"
    steps:
      - task: UsePythonVersion@0
        displayName: setup python
        inputs: { versionSpec: "3.8" }
      - task: TwineAuthenticate@1
        inputs:
          artifactFeed: ${{ parameters.artifact_feed }}
      - script: "python -m pip install --upgrade build twine"
        displayName: "acquire build tools"
      - script: 'python -m build'
        displayName: "build wheel and source distribution"
      - script: "python -m twine upload -r ${{ parameters.pypi_remote }} --config-file $(PYPIRC_PATH) dist/*.whl"
        displayName: "upload package to PyPi feed"
 